[package]
name = "Chainlink"
version = "0.1.0"
edition = "2024"

[dependencies]
chainlink-data-streams-sdk = "1.0.0"
chainlink-data-streams-report = "1.0.0"
tokio = { version = "1.4", features = ["full"] }
hex = "0.4"
dotenv = "0.15.0"
